### ISSUE TITLE
Is this using fargate? 

### ISSUE THREAD

**Issue by bmihaescu** [aws-samples/aws-stepfunctions-eks-fargate-process#1]
Hi, 

Nice work with the sample and blog post.
One question though, I'm looking over the eks.tf code and I don't see where do you configure the Fargate profile. 
Am I missing something or this is not for Fargate use? 

Thanks

**Comment by shivaramani** [comment]
Fargate profile and roles/policies are [roles.tf](https://github.com/aws-samples/aws-stepfunctions-eks-fargate-process/blob/main/templates/roles.tf#L116)
